name: Naming Rule

on:
  push:
    branches:
      - '**'   # 모든 브랜치에 대한 푸시를 감시
  pull_request:
    branches:
      - '**'   # 모든 브랜치에 대한 PR을 감시

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
        # 전체 커밋 히스토리를 가져옵니다.
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

        # 브랜치 이름 검사
      - name: Validate branch naming
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "develop" ]]; then
            echo "Skipping branch name validation for 'main' or 'develop' branch."
          elif [[ ! "$BRANCH_NAME" =~ ^(feature|release|hotfix)\/[a-zA-Z0-9_-]+$ ]]; then
            echo "❌ Branch name '$BRANCH_NAME' does not follow the naming convention."
            exit 1
          fi
          if [[ "$BRANCH_NAME" =~ [^a-zA-Z0-9_/-] ]]; then
            echo "❌ Branch name '$BRANCH_NAME' contains invalid characters."
            exit 1
          fi
          echo "✅ Branch name '$BRANCH_NAME' is valid."

        # 커밋 메시지 검사
      - name: Validate last commit messages
        run: |
          git log -1 --pretty=format:%s > last_commit_message.txt
          COMMIT_MSG=$(cat last_commit_message.txt)
          echo "Last commit message: $COMMIT_MSG"

          if [[ ! "$COMMIT_MSG" =~ ^(feat|fix|docs|style|refactor|test|chore|ci|build|perf|revert):\ .+ ]]; then
            echo "❌ Commit message '$COMMIT_MSG' does not follow the convention."
            exit 1
          fi
          echo "✅ Last commit messages are valid."
