name: Unity Test

on: [push, pull_request]

jobs:
  unity-tests:
    name: Run Unity Tests (PlayMode and EditMode)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        unityVersion:
          - 2022.3.13f1
        testMode:
          - playmode
          - editmode
    steps:
      ###########################
      #         Checkout        #
      ###########################
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      ###########################
      #         Setup Unity     #
      ###########################
      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}

      ###########################
      #          Cache          #
      ###########################
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.os }}-${{ matrix.unityVersion }}-${{ matrix.testMode }}
          restore-keys: |
            Library-${{ matrix.os }}-${{ matrix.unityVersion }}

      ###########################
      #     Run Unity Tests      #
      ###########################
      - name: Run ${{ matrix.testMode }} tests
        uses: game-ci/unity-test-runner@v3
        with:
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          customParameters: -projectPath . -logfile /dev/stdout