name: Unity Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2022.3.17f1

    - name: Run Unity tests Playmode
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: 2022.3.17f1
        testMode: playmode

    - name: Run Unity tests Editmode
      uses: game-ci/unity-test-runner@v2
      with:
        unityVersion: 2022.3.17f1
        testMode: editmode